version: '3.8'
services:
  api:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports: ["8000:8000"]
    env_file: ./backend/.env
  web:
    build: ./frontend
    command: npm run dev
    ports: ["3000:3000"]
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on: [api]n and update the 